# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master
 
pool:
  vmImage: windows-latest
 
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'
 
  - script: |
      cd '$(Build.SourcesDirectory)'
      npm install
    displayName: 'Install Dependencies'
 
  - script: |
      cd '$(Build.SourcesDirectory)'
      npm install -D @playwright/test
      npx playwright install
    displayName: 'Install Playwright'
 
  - script: |
      cd '$(build.SourcesDirectory)'
      npx playwright test
    displayName: 'Run Playwright Tests'
    continueOnError: true
 
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(build.sourcesdirectory)/playwright-report'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'
 
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
